name: Deploy to Azure Spring Apps

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy to production with .jar artifact
    steps:
      - name: Echo Azure Credentials
        run: echo ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: maven build, clean
        run: |
          mvn clean package

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production with artifact
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az spring app deployment create \
            --name green-deployment \
            --app ${{ secrets.APPLICATION_NAME }} \
            --service ${{ secrets.SERVICE_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --artifact-path target/*.jar
